// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec2 } from "./Vec2";

export type AbstractFrame = { origin_world: Vec2, x_dir: Vec2, y_dir: Vec2, dx: number, dy: number, stalls_per_face: number, };
