// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Real-valued point in an abstract frame.
 */
export type AbstractPoint2 = { x: number, y: number, };
