// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisleDirection } from "./AisleDirection";

export type AisleEdge = { start: number, end: number, width: number, interior: boolean, direction: AisleDirection, };
