// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisleDirection } from "./AisleDirection";
import type { Target } from "./Target";

export type Annotation = { "kind": "DeleteVertex", target: Target, } | { "kind": "DeleteEdge", target: Target, } | { "kind": "Direction", target: Target, 
/**
 * Direction in the *carrier's* canonical frame (Grid: low→high
 * along free axis; DriveLine: +t; Perimeter: +arc). The
 * pipeline translates this into the corresponding edge-frame
 * `AisleDirection` via `apply_*_direction` — which may map
 * `OneWay` → `OneWayReverse` (or vice versa) if the edge's
 * stored `(start, end)` order disagrees with carrier canonical.
 */
traffic: AisleDirection, };
