// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Target } from "./Target";
import type { TrafficDirection } from "./TrafficDirection";

export type Annotation = { "kind": "DeleteVertex", target: Target, } | { "kind": "DeleteEdge", target: Target, } | { "kind": "Direction", target: Target, traffic: TrafficDirection, };
