// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which axis the grid line's fixed coordinate is on. `axis=X, coord=c` is
 * the line x=c (fixed x; runs along Y). Canonical direction is +along the
 * "run axis" (low → high) — i.e. +Y for axis=X, +X for axis=Y.
 */
export type Axis = "X" | "Y";
