// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionId } from "./RegionId";

export type ChainLatticeEdge = { region: RegionId, xa: number, ya: number, xb: number, yb: number, };
