// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugToggles = { miter_fills: boolean, boundary_only_miters: boolean, spike_removal: boolean, contour_simplification: boolean, hole_filtering: boolean, face_simplification: boolean, edge_classification: boolean, spine_clipping: boolean, 
/**
 * Experimental: skip the weighted straight skeleton for boundary
 * faces and emit spines by offsetting each aisle-facing edge inward
 * by effective_depth, clipped to the face. Adjacent offset spines
 * whose tangents are close are grouped into placement paths so
 * discretized-arc aisles produce continuous stall rows instead of
 * per-chord spines that get filtered. Off = current behavior.
 */
offset_carriers: boolean, spine_dedup: boolean, spine_merging: boolean, paired_spine_normalization: boolean, short_spine_filter: boolean, spine_extensions: boolean, stall_centering: boolean, stall_face_clipping: boolean, entrance_on_face_filter: boolean, conflict_removal: boolean, island_stall_dilation: boolean, skeleton_debug: boolean, };
