// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugToggles = { miter_fills: boolean, boundary_only_miters: boolean, spike_removal: boolean, contour_simplification: boolean, hole_filtering: boolean, face_simplification: boolean, spine_clipping: boolean, 
/**
 * For BOUNDARY faces, skip the weighted straight skeleton and
 * emit spines by offsetting each aisle-facing edge inward by
 * effective_depth, clipped to the face. Adjacent offset spines
 * whose tangents are close are grouped into placement paths so
 * discretized-arc aisles produce continuous stall rows instead of
 * per-chord spines that get filtered. Default on; disable to fall
 * back to the skeleton path. Independent of
 * `offset_carriers_interior`.
 */
offset_carriers: boolean, 
/**
 * Same per-aisle-edge offset path, but for INTERIOR bays (faces
 * whose aisle-facing edges come from drive-lines / cross-aisles
 * rather than the perimeter aisle). Replaces the medial-axis
 * spine emission with rows aligned to each source aisle. Default
 * on; independent of `offset_carriers`.
 */
offset_carriers_interior: boolean, spine_dedup: boolean, spine_merging: boolean, paired_spine_normalization: boolean, short_spine_filter: boolean, spine_extensions: boolean, stall_centering: boolean, stall_face_clipping: boolean, entrance_on_face_filter: boolean, conflict_removal: boolean, island_stall_dilation: boolean, skeleton_debug: boolean, };
