// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugToggles = { miter_fills: boolean, boundary_only_miters: boolean, spike_removal: boolean, contour_simplification: boolean, hole_filtering: boolean, face_simplification: boolean, edge_classification: boolean, spine_clipping: boolean, spine_dedup: boolean, spine_merging: boolean, paired_spine_normalization: boolean, short_spine_filter: boolean, spine_extensions: boolean, stall_centering: boolean, stall_face_clipping: boolean, 
/**
 * When `stall_face_clipping` is on, only check the back half of each
 * stall (spine-side) against the face. The entrance half is allowed
 * to overhang the face boundary, which is fine for stalls whose
 * entrances naturally sit on or just past the aisle-side face edge.
 */
back_half_face_clipping: boolean, entrance_on_face_filter: boolean, conflict_removal: boolean, island_stall_dilation: boolean, skeleton_debug: boolean, };
