// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DormantAnnotation = { 
/**
 * Index into `GenerateInput.annotations`.
 */
index: number, 
/**
 * Why the annotation couldn't be applied this regen.
 */
reason: string, };
