// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HolePin } from "./HolePin";
import type { Vec2 } from "./Vec2";

export type DriveLine = { start: Vec2, end: Vec2, 
/**
 * When set, this drive line is a separator pinned to a hole vertex.
 */
holePin?: HolePin, 
/**
 * Stable identifier assigned by the UI at creation time. Splice
 * annotations key off this id + a fractional position along the
 * line, so the annotation survives rotation/stretch of the grid
 * even though splice vertices don't sit on the abstract grid.
 * Default 0 is the "no id" sentinel for legacy fixtures and is
 * never matched by splice annotations.
 */
id: number, 
/**
 * When true, this drive line participates in planar-arrangement
 * face enumeration and partitions the lot into regions. When
 * false, it's a corridor-only line (aisle graph edge, no
 * partitioning effect).
 */
partitions: boolean, };
