// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AisleEdge } from "./AisleEdge";
import type { Vec2 } from "./Vec2";

export type DriveAisleGraph = { vertices: Array<Vec2>, edges: Array<AisleEdge>, perim_vertex_count: number, };
