// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Circular arc along a polygon edge, AutoCAD-style bulge
 * parameterization. Edge i goes from `vertex[i]` to `vertex[(i+1) % n]`.
 * `bulge = sagitta / (chord_length / 2)` — `+1` is a semicircle on the
 * CCW side of the edge direction, `-1` a semicircle on the CW side,
 * `0` collapses to a straight line (and should be stored as `None`).
 */
export type EdgeArc = { bulge: number, };
