// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec2 } from "./Vec2";

export type Face = { contour: Array<Vec2>, holes: Array<Array<Vec2>>, is_boundary: boolean, 
/**
 * Per-edge source labels for debug visualization ("wall", "interior", "perimeter").
 */
edge_sources: Array<string>, 
/**
 * Per-hole per-edge source labels.
 */
hole_edge_sources: Array<Array<string>>, };
