// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";
import type { DebugToggles } from "./DebugToggles";
import type { DriveLine } from "./DriveLine";
import type { ParkingParams } from "./ParkingParams";
import type { Polygon } from "./Polygon";
import type { RegionOverride } from "./RegionOverride";
import type { StallModifier } from "./StallModifier";

export type GenerateInput = { boundary: Polygon, drive_lines: Array<DriveLine>, annotations: Array<Annotation>, params: ParkingParams, debug: DebugToggles, regionOverrides: Array<RegionOverride>, 
/**
 * User-drawn post-pass modifiers that retype or suppress overlapping
 * stalls (DESIGN §1.4). Empty = no-op. Applied after placement by
 * `pipeline::filter::apply_stall_modifiers`.
 */
stall_modifiers: Array<StallModifier>, };
