// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerimeterLoop } from "./PerimeterLoop";

/**
 * A stop along a grid line — either an integer lattice coord or a crossing
 * with another substrate. For crossings, resolution picks the first
 * crossing along the carrier's canonical direction from the other stop
 * (well-defined under the no-collinear-stretches constraint).
 */
export type GridStop = { "at": "Lattice", 
/**
 * Integer coord on the axis the line runs along.
 */
other: number, } | { "at": "CrossesDriveLine", id: number, } | { "at": "CrossesPerimeter", loop: PerimeterLoop, };
