// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParkingParams = { stall_width: number, stall_depth: number, aisle_width: number, stall_angle_deg: number, aisle_angle_deg: number, aisle_offset: number, site_offset: number, 
/**
 * Number of stalls along the aisle direction in one face — i.e.,
 * between adjacent cross driving aisles. Drives the canvas-space
 * length of a face along the aisle: dy = stalls_per_face *
 * stall_pitch. Was `cross_aisle_max_run` (a float in stall-pitch
 * units); now an integer count.
 */
stalls_per_face: number, use_regions: boolean, island_stall_interval: number, 
/**
 * Minimum stall count for a spine (primary + extensions combined)
 * to survive the short-segment filter. 1 is an effective no-op —
 * every spine with any stall meets the threshold.
 */
min_stalls_per_spine: number, };
