// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParkingParams = { stall_width: number, stall_depth: number, aisle_width: number, stall_angle: number, aisle_angle: number, aisle_offset: number, site_offset: number, 
/**
 * Number of stalls along the aisle direction in one face — i.e.,
 * between adjacent cross driving aisles. Drives the canvas-space
 * length of a face along the aisle: dy = stalls_per_face *
 * stall_pitch.
 */
stalls_per_face: number, use_regions: boolean, island_stall_interval: number, 
/**
 * Minimum stall count for a spine (primary + extensions combined)
 * to survive the short-segment filter. 1 is an effective no-op —
 * every spine with any stall meets the threshold.
 */
min_stalls_per_spine: number, 
/**
 * Chord-deflection tolerance (feet) used when discretizing curved
 * boundary edges into straight-line polylines. Smaller = smoother
 * arcs but more perimeter vertices. See `geom::arc::discretize_polygon`.
 */
arc_discretize_tolerance: number, 
/**
 * Maximum angular difference (degrees) between two spine segments
 * for them to be considered colinear and fused. Controls how
 * aggressively chord-derived spines along a discretized arc collapse
 * into a single straight segment in `try_merge_spines`.
 */
spine_merge_angle_deg: number, 
/**
 * Endpoint-share tolerance (feet) for the spine-merge pass. Two
 * spines must have a pair of endpoints within this distance to be
 * candidates for fusion in `merge_collinear_spines`.
 */
spine_merge_endpoint_tol: number, 
/**
 * Turn radius (feet) for island corner rounding. A disk of this
 * radius is rolled inside each face polygon (morphological
 * opening) before residual island extraction, so convex face
 * corners become arcs rather than 90° wedges. Only takes effect
 * when `DebugToggles.island_corner_rounding` is on.
 */
island_corner_radius: number, 
/**
 * ADA accessible stall width (feet). When a stall-modifier line
 * retypes a stall to `Ada`, its quad is widened symmetrically
 * from `stall_width` up to this value. Real ADA spec is ~13ft for
 * regular and ~16ft for van-accessible (incl. striped aisle).
 */
ada_stall_width: number, 
/**
 * Compact stall width (feet). Narrower than `stall_width` —
 * typical real-world compact stalls are 7.5–8 ft. The same
 * per-row reflow that handles ADA widening also handles compact
 * narrowing: neighbors shift inward to absorb the freed space.
 */
compact_stall_width: number, 
/**
 * ADA access-aisle width (feet) — the striped no-park zone next
 * to each ADA stall. Real spec: 5 ft for car spaces, 8 ft for
 * van-accessible. Set 0 to disable.
 */
ada_buffer_width: number, 
/**
 * When true, two adjacent ADA stalls share one buffer between
 * them: `[ADA][buf][ADA][buf][ADA]`. When false, each ADA stall
 * gets its own buffer: `[ADA][buf][ADA][buf][ADA][buf]`.
 */
ada_buffer_shared: boolean, };
