// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriveAisleGraph } from "./DriveAisleGraph";
import type { Face } from "./Face";
import type { Island } from "./Island";
import type { Metrics } from "./Metrics";
import type { RegionDebug } from "./RegionDebug";
import type { SpineLine } from "./SpineLine";
import type { StallQuad } from "./StallQuad";
import type { Vec2 } from "./Vec2";

export type ParkingLayout = { stalls: Array<StallQuad>, metrics: Metrics, resolved_graph: DriveAisleGraph, spines: Array<SpineLine>, faces: Array<Face>, miter_fills: Array<Array<Vec2>>, islands: Array<Island>, 
/**
 * Raw lot boundary derived by expanding the aisle-edge perimeter outward.
 */
derived_outer: Array<Vec2>, 
/**
 * Raw building footprints derived by shrinking aisle-edge rings inward.
 */
derived_holes: Array<Array<Vec2>>, 
/**
 * Debug: region clip polygons and separator segments for visualization.
 */
region_debug: RegionDebug | null, 
/**
 * Indices into `GenerateInput.annotations` for annotations that
 * didn't resolve to any graph feature in this pass. For abstract
 * annotations that means the (region, xi, yi) lookup missed —
 * the target grid point isn't inside any current region, or the
 * region's clip polygon excludes it. For legacy proximity
 * annotations it means no edge/vertex landed within the
 * proximity threshold. Either way the annotation is stored but
 * not applied this regenerate; the UI can surface these as
 * "dormant."
 */
dormant_annotations: Array<number>, };
