// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A perimeter loop on the sketch boundary: the unique outer boundary, or
 * a specific hole. In the prototype, holes are identified positionally;
 * the Arcol integration uses a stable member sketch-vertex id instead.
 */
export type PerimeterLoop = { "kind": "Outer" } | { "kind": "Hole", index: number, };
