// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerimeterLoop } from "./PerimeterLoop";

export type PerimeterPosResult = { loop: PerimeterLoop, arc: number, };
