// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerimeterLoop } from "./PerimeterLoop";
import type { VertexId } from "./VertexId";

export type PerimeterPosResult = { loop: PerimeterLoop, 
/**
 * Sketch vertex at the start of the addressed edge.
 */
start: VertexId, 
/**
 * Sketch vertex at the end of the addressed edge.
 */
end: VertexId, 
/**
 * Position along the chord chain from `start` to `end` ∈ [0, 1].
 */
t: number, };
