// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeArc } from "./EdgeArc";
import type { Vec2 } from "./Vec2";
import type { VertexId } from "./VertexId";

export type Polygon = { outer: Array<Vec2>, holes: Array<Array<Vec2>>, 
/**
 * Per-edge arc data for outer boundary. Parallel to `outer` edges.
 */
outer_arcs: Array<EdgeArc | null>, 
/**
 * Per-hole per-edge arc data. Outer index = hole index.
 */
hole_arcs: Array<Array<EdgeArc | null>>, 
/**
 * Per-vertex stable ids for the outer ring. Parallel to `outer`.
 * Auto-allocated by `ensure_ids` if missing on input.
 */
outer_ids: Array<VertexId>, 
/**
 * Per-vertex stable ids for each hole. Parallel to `holes`.
 */
hole_ids: Array<Array<VertexId>>, };
