// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeArc } from "./EdgeArc";
import type { Vec2 } from "./Vec2";

export type Polygon = { outer: Array<Vec2>, holes: Array<Array<Vec2>>, 
/**
 * Per-edge arc data for outer boundary. Parallel to `outer` edges.
 */
outer_arcs: Array<EdgeArc | null>, 
/**
 * Per-hole per-edge arc data. Outer index = hole index.
 */
hole_arcs: Array<Array<EdgeArc | null>>, };
