// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionInfo } from "./RegionInfo";
import type { Vec2 } from "./Vec2";

export type RegionDebug = { 
/**
 * One clip polygon per region, each with its aisle angle.
 */
regions: Array<RegionInfo>, 
/**
 * Separator line segments (hole corner → shortened endpoint).
 */
separators: Array<[Vec2, Vec2]>, };
