// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionId } from "./RegionId";

export type RegionOverride = { region_id: RegionId, aisle_angle_deg?: number, aisle_offset?: number, };
