// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionId } from "./RegionId";
import type { Vec2 } from "./Vec2";

export type RegionInfo = { id: RegionId, clip_poly: Array<Vec2>, aisle_angle: number, aisle_offset: number, center: Vec2, };
