// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec2 } from "./Vec2";

export type SkeletonDebug = { arcs: Array<[Vec2, Vec2]>, nodes: Array<Vec2>, 
/**
 * Split event points where the wavefront separated into independent regions.
 */
split_nodes: Array<Vec2>, 
/**
 * Original polygon vertices from which skeleton arcs originate.
 */
sources: Array<Vec2>, };
