// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec2 } from "./Vec2";

export type SpineLine = { start: Vec2, end: Vec2, normal: Vec2, is_extension: boolean, };
