// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StallKind } from "./StallKind";
import type { Vec2 } from "./Vec2";

/**
 * Post-placement modifier applied to stalls whose geometry overlaps
 * the modifier's polyline.
 *
 * - `kind = Suppressed` + a polyline → remove stalls from rendering
 *   (used for fire lanes, loading zones, entrance corridors).
 * - Any other `kind` → retype overlapping stalls (ADA, EV, Island).
 *   A zero-length polyline (single point) places a single retyped
 *   stall at that location.
 */
export type StallModifier = { polyline: Array<Vec2>, kind: StallKind, };
