// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StallKind } from "./StallKind";
import type { Vec2 } from "./Vec2";

export type StallQuad = { corners: [Vec2, Vec2, Vec2, Vec2], kind: StallKind, };
