// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Axis } from "./Axis";
import type { GridStop } from "./GridStop";
import type { PerimeterLoop } from "./PerimeterLoop";
import type { RegionId } from "./RegionId";

/**
 * A referenceable region in one substrate's own coord system.
 * - Grid.range = None     → whole grid line (edge annotations only).
 * - Grid.range = Some((s, s)) → a vertex.
 * - Grid.range = Some((s1, s2)), s1 != s2 → a span of sub-edges.
 * - DriveLine / Perimeter: a single parametric point. Vertex annotations
 *   resolve to the graph vertex at the point (if one exists); edge
 *   annotations resolve to the sub-edge containing the point.
 */
export type Target = { "on": "Grid", region: RegionId, axis: Axis, coord: number, 
/**
 * None = whole grid line; Some((s, s)) = vertex; Some((s1, s2)) = span.
 */
range: [GridStop, GridStop] | null, } | { "on": "DriveLine", id: number, 
/**
 * Parametric t ∈ [0, 1] from drive_line.start → drive_line.end.
 */
t: number, } | { "on": "Perimeter", loop: PerimeterLoop, 
/**
 * Normalized arc length ∈ [0, 1] along the loop.
 */
arc: number, };
