// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for a sketch vertex. Allocated at input parse
 * time and threaded through the pipeline so that perimeter
 * annotations can address sketch edges as `(start, end)` pairs
 * instead of by array index or arc length. Mirrors Arcol's
 * `VertexId` (a `Brand<number, "VertexId">` over a 32-bit
 * integer) for an eventual integration.
 *
 * Ids are stable within a single user-authored sketch — they
 * survive vertex insertion, deletion, and reordering elsewhere on
 * the loop. Splitting an edge with a new sketch vertex *does*
 * invalidate the original edge identity; resolution promotes the
 * annotation onto the appropriate child edge by length.
 *
 * Post-discretization vertices that don't correspond to a sketch
 * corner carry synthetic ids — they're not addressable from
 * annotations but exist so that the parallel `outer_ids` /
 * `hole_ids` arrays stay 1:1 with the vertex lists.
 */
export type VertexId = number;
