//! `#[wasm_bindgen]` facade. The only place the engine talks to
//! JavaScript; all engine logic is native-testable without wasm-pack.
//!
//! Pattern for structured JS interop:
//! - Flat `f64` arguments for per-point math (arc primitives) — zero
//!   marshaling cost, matches the hot-path shape most callers already
//!   have on the JS side.
//! - `serde-wasm-bindgen` round-trip for compound structs
//!   (ParkingParams, AbstractFrame, Vec2) so the TS types generated by
//!   ts-rs line up with the JS values passed back and forth.

use wasm_bindgen::prelude::*;

use crate::debug::format_fixture;
use crate::geom::arc::{arc_apex, bulge_from_apex, eval_arc_at, project_to_arc};
use crate::geom::poly::point_to_segment_dist;
use crate::pipeline::generate::generate;
use crate::resolve;
use crate::types::{
    AbstractFrame, AbstractPoint2, Annotation, DriveAisleGraph, DriveLine, GenerateInput,
    ParkingParams, Polygon, RegionDebug, RegionInfo, Target, Vec2,
};

#[wasm_bindgen]
pub fn generate_js(input_json: &str) -> String {
    let input: GenerateInput = serde_json::from_str(input_json).unwrap();
    let layout = generate(input);
    serde_json::to_string(&layout).unwrap()
}

/// Serialize a `GenerateInput` JSON into the datadriven test fixture format
/// used by `tests/testdata/*.txt`. Call from the browser console:
///   copy(debug_input_js(window.__parkingInput))
/// Then paste into a new .txt file under `tests/testdata/`.
#[wasm_bindgen]
pub fn debug_input_js(input_json: &str) -> String {
    let input: GenerateInput = serde_json::from_str(input_json).unwrap();
    format_fixture(&input)
}

// ---------------------------------------------------------------------------
// Arc math — flat-f64 args keep this cheap in the per-frame render path.
// The renderer calls `arc_apex_js` per curved boundary edge; we don't
// want a serde round-trip on each one.
//
// `project_to_arc_js` returns `[t, x, y]` — a flat triple the TS caller
// unpacks once. Keeping the output packed avoids a second allocation
// for the `{pos, t}` wrapper.
// ---------------------------------------------------------------------------

#[wasm_bindgen]
pub fn arc_apex_js(p0x: f64, p0y: f64, p1x: f64, p1y: f64, bulge: f64) -> Vec<f64> {
    let apex = arc_apex(Vec2::new(p0x, p0y), Vec2::new(p1x, p1y), bulge);
    vec![apex.x, apex.y]
}

#[wasm_bindgen]
pub fn bulge_from_apex_js(
    p0x: f64, p0y: f64, p1x: f64, p1y: f64, apex_x: f64, apex_y: f64,
) -> f64 {
    bulge_from_apex(
        Vec2::new(p0x, p0y),
        Vec2::new(p1x, p1y),
        Vec2::new(apex_x, apex_y),
    )
}

#[wasm_bindgen]
pub fn eval_arc_at_js(
    p0x: f64, p0y: f64, p1x: f64, p1y: f64, bulge: f64, t: f64,
) -> Vec<f64> {
    let p = eval_arc_at(Vec2::new(p0x, p0y), Vec2::new(p1x, p1y), bulge, t);
    vec![p.x, p.y]
}

#[wasm_bindgen]
pub fn project_to_arc_js(
    p0x: f64, p0y: f64, p1x: f64, p1y: f64, bulge: f64, ptx: f64, pty: f64,
) -> Vec<f64> {
    let (pos, t) = project_to_arc(
        Vec2::new(p0x, p0y),
        Vec2::new(p1x, p1y),
        bulge,
        Vec2::new(ptx, pty),
    );
    vec![t, pos.x, pos.y]
}

// ---------------------------------------------------------------------------
// Frame math — compound types flow through serde-wasm-bindgen so the
// TS bindings and Rust structs stay structurally identical. AbstractFrame
// isn't free to construct (6 fields × trig), but the caller builds one
// and reuses it across many forward/inverse queries, so marshaling cost
// is amortized.
// ---------------------------------------------------------------------------

#[wasm_bindgen]
pub fn compute_region_frame_js(
    params: JsValue,
    aisle_angle_deg: f64,
    aisle_offset: f64,
) -> Result<JsValue, JsValue> {
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    let frame = AbstractFrame::region(&params, aisle_angle_deg, aisle_offset);
    Ok(serde_wasm_bindgen::to_value(&frame)?)
}

#[wasm_bindgen]
pub fn frame_forward_js(frame: JsValue, px: f64, py: f64) -> Result<Vec<f64>, JsValue> {
    let frame: AbstractFrame = serde_wasm_bindgen::from_value(frame)?;
    let world = frame.forward(AbstractPoint2 { x: px, y: py });
    Ok(vec![world.x, world.y])
}

#[wasm_bindgen]
pub fn frame_inverse_js(frame: JsValue, wx: f64, wy: f64) -> Result<Vec<f64>, JsValue> {
    let frame: AbstractFrame = serde_wasm_bindgen::from_value(frame)?;
    let abs = frame.inverse(Vec2::new(wx, wy));
    Ok(vec![abs.x, abs.y])
}

// ---------------------------------------------------------------------------
// Params-derived scalars. Cheap enough that JSON-parsing params each
// call is overkill — serde-wasm-bindgen keeps this minimal.
// ---------------------------------------------------------------------------

#[wasm_bindgen]
pub fn stall_pitch_js(params: JsValue) -> Result<f64, JsValue> {
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    Ok(params.stall_pitch())
}

#[wasm_bindgen]
pub fn effective_depth_js(params: JsValue) -> Result<f64, JsValue> {
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    Ok(params.effective_depth())
}

// ---------------------------------------------------------------------------
// Substrate resolution (engine/src/resolve.rs). Target ↔ world,
// world → substrate address, chain → lattice-edge extents.
// ---------------------------------------------------------------------------

/// `resolve::target_world_pos` — returns `{x, y}` or `null`.
#[wasm_bindgen]
pub fn target_world_pos_js(
    target: JsValue,
    boundary: JsValue,
    drive_lines: JsValue,
    region_debug: JsValue,
    params: JsValue,
) -> Result<JsValue, JsValue> {
    let target: Target = serde_wasm_bindgen::from_value(target)?;
    let boundary: Polygon = serde_wasm_bindgen::from_value(boundary)?;
    let drive_lines: Vec<DriveLine> = serde_wasm_bindgen::from_value(drive_lines)?;
    let region_debug: Option<RegionDebug> = serde_wasm_bindgen::from_value(region_debug)?;
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    let pos = resolve::target_world_pos(
        &target,
        &boundary,
        &drive_lines,
        region_debug.as_ref(),
        &params,
    );
    Ok(serde_wasm_bindgen::to_value(&pos)?)
}

/// `resolve::annotation_world_pos` — thin wrapper that pulls the
/// annotation's target and forwards to target_world_pos_js.
#[wasm_bindgen]
pub fn annotation_world_pos_js(
    ann: JsValue,
    boundary: JsValue,
    drive_lines: JsValue,
    region_debug: JsValue,
    params: JsValue,
) -> Result<JsValue, JsValue> {
    let ann: Annotation = serde_wasm_bindgen::from_value(ann)?;
    let boundary: Polygon = serde_wasm_bindgen::from_value(boundary)?;
    let drive_lines: Vec<DriveLine> = serde_wasm_bindgen::from_value(drive_lines)?;
    let region_debug: Option<RegionDebug> = serde_wasm_bindgen::from_value(region_debug)?;
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    let pos = resolve::annotation_world_pos(
        &ann,
        &boundary,
        &drive_lines,
        region_debug.as_ref(),
        &params,
    );
    Ok(serde_wasm_bindgen::to_value(&pos)?)
}

/// `resolve::world_to_abstract_vertex` — returns
/// `{region, xi, yi}` or `null`.
#[wasm_bindgen]
pub fn world_to_abstract_vertex_js(
    wx: f64,
    wy: f64,
    params: JsValue,
    region_debug: JsValue,
    snap_tol_world: f64,
) -> Result<JsValue, JsValue> {
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    let region_debug: Option<RegionDebug> = serde_wasm_bindgen::from_value(region_debug)?;
    let result = resolve::world_to_abstract_vertex(
        Vec2::new(wx, wy),
        &params,
        region_debug.as_ref(),
        snap_tol_world,
    );
    Ok(serde_wasm_bindgen::to_value(&result)?)
}

/// `resolve::world_to_splice_vertex` — returns
/// `{drive_line_id, t}` or `null`.
#[wasm_bindgen]
pub fn world_to_splice_vertex_js(
    wx: f64,
    wy: f64,
    drive_lines: JsValue,
    snap_tol_world: f64,
) -> Result<JsValue, JsValue> {
    let drive_lines: Vec<DriveLine> = serde_wasm_bindgen::from_value(drive_lines)?;
    let result = resolve::world_to_splice_vertex(Vec2::new(wx, wy), &drive_lines, snap_tol_world);
    Ok(serde_wasm_bindgen::to_value(&result)?)
}

/// `resolve::world_to_perimeter_pos` — returns
/// `{loop, arc}` or `null`.
#[wasm_bindgen]
pub fn world_to_perimeter_pos_js(
    wx: f64,
    wy: f64,
    boundary: JsValue,
    tol: f64,
) -> Result<JsValue, JsValue> {
    let boundary: Polygon = serde_wasm_bindgen::from_value(boundary)?;
    let result = resolve::world_to_perimeter_pos(Vec2::new(wx, wy), &boundary, tol);
    Ok(serde_wasm_bindgen::to_value(&result)?)
}

#[wasm_bindgen]
pub fn chain_to_abstract_lattice_edge_js(
    chain_points: JsValue,
    params: JsValue,
    region_debug: JsValue,
) -> Result<JsValue, JsValue> {
    let chain_points: Vec<Vec2> = serde_wasm_bindgen::from_value(chain_points)?;
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    let region_debug: Option<RegionDebug> = serde_wasm_bindgen::from_value(region_debug)?;
    let result =
        resolve::chain_to_abstract_lattice_edge(&chain_points, &params, region_debug.as_ref());
    Ok(serde_wasm_bindgen::to_value(&result)?)
}

#[wasm_bindgen]
pub fn chain_extents_in_region_js(
    chain_points: JsValue,
    params: JsValue,
    region: JsValue,
) -> Result<JsValue, JsValue> {
    let chain_points: Vec<Vec2> = serde_wasm_bindgen::from_value(chain_points)?;
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    let region: RegionInfo = serde_wasm_bindgen::from_value(region)?;
    let result = resolve::chain_extents_in_region(&chain_points, &params, &region);
    Ok(serde_wasm_bindgen::to_value(&result)?)
}

// ---------------------------------------------------------------------------
// Point-in-polygon primitive. Pure geometry; exposed so the UI can
// drop its hand-rolled copy.
// ---------------------------------------------------------------------------

#[wasm_bindgen]
pub fn point_in_polygon_js(px: f64, py: f64, poly: JsValue) -> Result<bool, JsValue> {
    let poly: Vec<Vec2> = serde_wasm_bindgen::from_value(poly)?;
    Ok(crate::geom::clip::point_in_polygon(
        &Vec2::new(px, py),
        &poly,
    ))
}

/// Distance from point `(px, py)` to the segment `(ax, ay) → (bx, by)`.
#[wasm_bindgen]
pub fn point_to_segment_dist_js(
    px: f64, py: f64, ax: f64, ay: f64, bx: f64, by: f64,
) -> f64 {
    point_to_segment_dist(Vec2::new(px, py), Vec2::new(ax, ay), Vec2::new(bx, by))
}

/// `resolve::hit_test_edge` — returns the deduplicated edge index
/// or `null` if no edge is within `world_radius`.
#[wasm_bindgen]
pub fn hit_test_edge_js(
    wx: f64,
    wy: f64,
    graph: JsValue,
    world_radius: f64,
) -> Result<JsValue, JsValue> {
    let graph: DriveAisleGraph = serde_wasm_bindgen::from_value(graph)?;
    let result = resolve::hit_test_edge(Vec2::new(wx, wy), &graph, world_radius);
    Ok(serde_wasm_bindgen::to_value(&result)?)
}

/// `resolve::find_collinear_chain` — deduplicated edge indices on the
/// same collinear run as `seed_idx`.
#[wasm_bindgen]
pub fn find_collinear_chain_js(
    graph: JsValue,
    seed_idx: usize,
) -> Result<Vec<usize>, JsValue> {
    let graph: DriveAisleGraph = serde_wasm_bindgen::from_value(graph)?;
    Ok(resolve::find_collinear_chain(&graph, seed_idx))
}

/// `resolve::resolve_grid_target` — from an edge selection (seed +
/// chain + mode) to a `Target::Grid`, or null if the selection doesn't
/// sit on grid-aligned lattice vertices.
#[wasm_bindgen]
pub fn resolve_grid_target_js(
    seed_index: usize,
    chain: Vec<usize>,
    is_chain_mode: bool,
    graph: JsValue,
    params: JsValue,
    region_debug: JsValue,
) -> Result<JsValue, JsValue> {
    let graph: DriveAisleGraph = serde_wasm_bindgen::from_value(graph)?;
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    let region_debug: Option<RegionDebug> = serde_wasm_bindgen::from_value(region_debug)?;
    let result = match region_debug.as_ref() {
        Some(rd) => resolve::resolve_grid_target(seed_index, &chain, is_chain_mode, &graph, &params, rd),
        None => None,
    };
    Ok(serde_wasm_bindgen::to_value(&result)?)
}

/// `resolve::targets_equal` — structural equality over `Target`.
#[wasm_bindgen]
pub fn targets_equal_js(a: JsValue, b: JsValue) -> Result<bool, JsValue> {
    let a: Target = serde_wasm_bindgen::from_value(a)?;
    let b: Target = serde_wasm_bindgen::from_value(b)?;
    Ok(resolve::targets_equal(&a, &b))
}
