//! `#[wasm_bindgen]` facade. The only place the engine talks to
//! JavaScript; all engine logic is native-testable without wasm-pack.
//!
//! Pattern for structured JS interop:
//! - Flat `f64` arguments for per-point math (arc primitives) — zero
//!   marshaling cost, matches the hot-path shape most callers already
//!   have on the JS side.
//! - `serde-wasm-bindgen` round-trip for compound structs
//!   (ParkingParams, AbstractFrame, Vec2) so the TS types generated by
//!   ts-rs line up with the JS values passed back and forth.

use wasm_bindgen::prelude::*;

use crate::debug::format_fixture;
use crate::geom::arc::{arc_apex, bulge_from_apex, eval_arc_at, project_to_arc};
use crate::pipeline::generate::generate;
use crate::types::{AbstractFrame, AbstractPoint2, GenerateInput, ParkingParams, Vec2};

#[wasm_bindgen]
pub fn generate_js(input_json: &str) -> String {
    let input: GenerateInput = serde_json::from_str(input_json).unwrap();
    let layout = generate(input);
    serde_json::to_string(&layout).unwrap()
}

/// Serialize a `GenerateInput` JSON into the datadriven test fixture format
/// used by `tests/testdata/*.txt`. Call from the browser console:
///   copy(debug_input_js(window.__parkingInput))
/// Then paste into a new .txt file under `tests/testdata/`.
#[wasm_bindgen]
pub fn debug_input_js(input_json: &str) -> String {
    let input: GenerateInput = serde_json::from_str(input_json).unwrap();
    format_fixture(&input)
}

// ---------------------------------------------------------------------------
// Arc math — flat-f64 args keep this cheap in the per-frame render path.
// The renderer calls `arc_apex_js` per curved boundary edge; we don't
// want a serde round-trip on each one.
//
// `project_to_arc_js` returns `[t, x, y]` — a flat triple the TS caller
// unpacks once. Keeping the output packed avoids a second allocation
// for the `{pos, t}` wrapper.
// ---------------------------------------------------------------------------

#[wasm_bindgen]
pub fn arc_apex_js(p0x: f64, p0y: f64, p1x: f64, p1y: f64, bulge: f64) -> Vec<f64> {
    let apex = arc_apex(Vec2::new(p0x, p0y), Vec2::new(p1x, p1y), bulge);
    vec![apex.x, apex.y]
}

#[wasm_bindgen]
pub fn bulge_from_apex_js(
    p0x: f64, p0y: f64, p1x: f64, p1y: f64, apex_x: f64, apex_y: f64,
) -> f64 {
    bulge_from_apex(
        Vec2::new(p0x, p0y),
        Vec2::new(p1x, p1y),
        Vec2::new(apex_x, apex_y),
    )
}

#[wasm_bindgen]
pub fn eval_arc_at_js(
    p0x: f64, p0y: f64, p1x: f64, p1y: f64, bulge: f64, t: f64,
) -> Vec<f64> {
    let p = eval_arc_at(Vec2::new(p0x, p0y), Vec2::new(p1x, p1y), bulge, t);
    vec![p.x, p.y]
}

#[wasm_bindgen]
pub fn project_to_arc_js(
    p0x: f64, p0y: f64, p1x: f64, p1y: f64, bulge: f64, ptx: f64, pty: f64,
) -> Vec<f64> {
    let (pos, t) = project_to_arc(
        Vec2::new(p0x, p0y),
        Vec2::new(p1x, p1y),
        bulge,
        Vec2::new(ptx, pty),
    );
    vec![t, pos.x, pos.y]
}

// ---------------------------------------------------------------------------
// Frame math — compound types flow through serde-wasm-bindgen so the
// TS bindings and Rust structs stay structurally identical. AbstractFrame
// isn't free to construct (6 fields × trig), but the caller builds one
// and reuses it across many forward/inverse queries, so marshaling cost
// is amortized.
// ---------------------------------------------------------------------------

#[wasm_bindgen]
pub fn compute_region_frame_js(
    params: JsValue,
    aisle_angle_deg: f64,
    aisle_offset: f64,
) -> Result<JsValue, JsValue> {
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    let frame = AbstractFrame::region(&params, aisle_angle_deg, aisle_offset);
    Ok(serde_wasm_bindgen::to_value(&frame)?)
}

#[wasm_bindgen]
pub fn frame_forward_js(frame: JsValue, px: f64, py: f64) -> Result<Vec<f64>, JsValue> {
    let frame: AbstractFrame = serde_wasm_bindgen::from_value(frame)?;
    let world = frame.forward(AbstractPoint2 { x: px, y: py });
    Ok(vec![world.x, world.y])
}

#[wasm_bindgen]
pub fn frame_inverse_js(frame: JsValue, wx: f64, wy: f64) -> Result<Vec<f64>, JsValue> {
    let frame: AbstractFrame = serde_wasm_bindgen::from_value(frame)?;
    let abs = frame.inverse(Vec2::new(wx, wy));
    Ok(vec![abs.x, abs.y])
}

// ---------------------------------------------------------------------------
// Params-derived scalars. Cheap enough that JSON-parsing params each
// call is overkill — serde-wasm-bindgen keeps this minimal.
// ---------------------------------------------------------------------------

#[wasm_bindgen]
pub fn stall_pitch_js(params: JsValue) -> Result<f64, JsValue> {
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    Ok(params.stall_pitch())
}

#[wasm_bindgen]
pub fn effective_depth_js(params: JsValue) -> Result<f64, JsValue> {
    let params: ParkingParams = serde_wasm_bindgen::from_value(params)?;
    Ok(params.effective_depth())
}
